### ISSUE TITLE
Missing ssh_config dependency

### ISSUE THREAD

**Issue by alain-hoang** [apuigsech/seekret-source-git#2]
It appears that the ssh_config is no longer available at the referenced url which causes brand new attempts to build this library or using 'go get' to install this library to fail.

`[ERROR]    Update failed for github.com/jasonmoo/ssh_config: Unable to update repository
 [ERROR]    Failed to do initial checkout of config: Unable to update repository`

**Comment by alain-hoang** [comment]
Created a PR (#3) that updates to a location that can pull down the library.  I have also created a transitory fork for the ssh_config library available at [here](https://github.com/alain-hoang/ssh_config)

**Comment by alain-hoang** [comment]
ssh_config library has been moved.  More info [here](https://github.com/emptyinterface/sshconfig)

**Comment by apuigsech** [comment]
Fixed! Thanks!
